version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: covid_vaccine_db
      MYSQL_ROOT_PASSWORD: password
    ports:
       - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

